<a href="https://colab.research.google.com/github/LikhithaKakuluri/Singularium_Task1/blob/main/Singularium_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Dependencies**

In [1]:
import pandas as pd
import json
from collections import defaultdict

In [82]:
df=pd.read_csv("classification.csv")
df

,meta_row_data,verification_messages,classification_1,classification_2,classification_3,order,jpg_url,file_name,meta_verification_messages,meta_classification_1,meta_classification_2,meta_classification_3,meta_order,meta_jpg_url,meta_file_name
0,"{""type"": ""hidden"", ""title"": ""meta_row_data"", ""...","{""type"": ""text"", ""title"": ""verification_messag...","{""type"": ""text"", ""title"": ""classification_1"", ...","{""type"": ""text"", ""title"": ""classification_2"", ...","{""type"": ""text"", ""title"": ""classification_3"", ...","{""type"": ""text"", ""title"": ""order"", ""name"": ""5""...","{""type"": ""hidden"", ""title"": ""jpg_url"", ""name"":...","{""type"": ""text"", ""title"": ""file_name"", ""name"":...","{""type"": ""hidden"", ""title"": ""meta_verification...","{""type"": ""hidden"", ""title"": ""meta_classificati...","{""type"": ""hidden"", ""title"": ""meta_classificati...","{""type"": ""hidden"", ""title"": ""meta_classificati...","{""type"": ""hidden"", ""title"": ""meta_order"", ""nam...","{""type"": ""hidden"", ""title"": ""meta_jpg_url"", ""n...","{""type"": ""hidden"", ""title"": ""meta_file_name"", ..."
1,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,ECG,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,AADHAAR,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,AADHAAR,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,TRF,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,MER,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,MER,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,MER,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,PHOTO,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,CBC,PATHOLOGY,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,CBC,PATHOLOGY,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,PATHOLOGY,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,HBA1C,PATHOLOGY,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,PATHOLOGY,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,PATHOLOGY,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,PATHOLOGY,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,PATHOLOGY,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,HDL,PATHOLOGY,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,PATHOLOGY,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,PATHOLOGY,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,RUA-MX,PATHOLOGY,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,RUA-MX,PATHOLOGY,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",Possible Name Mismatch,URINE COTININE,PATHOLOGY,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"{""onselect"": {""updateCanvas"": {""ws"": ""images"",...",NaN,IGNORE,NaN,NaN,0,https://dostbucketprod.s3.amazonaws.com/defaul...,60224472_22,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
columns_to_drop = ['meta_row_data', 'verification_messages','order', 'jpg_url','meta_verification_messages', 'meta_classification_1',
       'meta_classification_2', 'meta_classification_3', 'meta_order',
       'meta_jpg_url', 'meta_file_name']

df1 = df.drop(columns=columns_to_drop)

# Save the updated CSV file
output_csv = "/content/updated_classification.csv"
df1.to_csv(output_csv, index=False)

In [84]:
df1

,classification_1,classification_2,classification_3,file_name
0,"{""type"": ""text"", ""title"": ""classification_1"", ...","{""type"": ""text"", ""title"": ""classification_2"", ...","{""type"": ""text"", ""title"": ""classification_3"", ...","{""type"": ""text"", ""title"": ""file_name"", ""name"":..."
1,ECG,NaN,NaN,60224472_0
2,AADHAAR,NaN,NaN,60224472_1
3,AADHAAR,NaN,NaN,60224472_2
4,TRF,NaN,NaN,60224472_3
5,MER,NaN,NaN,60224472_4
6,MER,NaN,NaN,60224472_5
7,MER,NaN,NaN,60224472_6
8,PHOTO,NaN,NaN,60224472_7
9,CBC,PATHOLOGY,NaN,60224472_8
10,CBC,PATHOLOGY,NaN,60224472_9
11,PATHOLOGY,NaN,NaN,60224472_10
12,HBA1C,PATHOLOGY,NaN,60224472_11
13,PATHOLOGY,NaN,NaN,60224472_12
14,PATHOLOGY,NaN,NaN,60224472_13
15,PATHOLOGY,NaN,NaN,60224472_14
16,PATHOLOGY,NaN,NaN,60224472_15
17,HDL,PATHOLOGY,NaN,60224472_16
18,PATHOLOGY,NaN,NaN,60224472_17
19,PATHOLOGY,NaN,NaN,60224472_18
20,RUA-MX,PATHOLOGY,NaN,60224472_19
21,RUA-MX,PATHOLOGY,NaN,60224472_20
22,URINE COTININE,PATHOLOGY,NaN,60224472_21
23,IGNORE,NaN,NaN,60224472_22

In [85]:
# Load JSON file (replace 'file.json' with your file path)
with open('tag_outputs.json', 'r') as f:
    json_data = json.load(f)

In [86]:
json_df = pd.DataFrame(json_data)

json_df

,key,class,sub_class,features,name,age,gender,mask,name_match_score,doc_date
0,60224472_0,ECG,,,Bharani Raj Thiagarajan,44.0,male,[],0.25,05012025
1,60224472_1,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.17,20031980
2,60224472_2,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.25,NaN
3,60224472_3,STATIC_FORM,TRF,,NaN,NaN,NaN,[],0.25,08NaN2011
4,60224472_4,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,20031980
5,60224472_5,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,NaN
6,60224472_6,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,08012025
7,60224472_7,PHOTO,,"[""face"", ""geo_tag"", ""full_body_image""]",NaN,NaN,NaN,[],0.25,05012025
8,60224472_8,PATHOLOGY,CBC|PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
9,60224472_9,PATHOLOGY,CBC,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
10,60224472_10,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
11,60224472_11,PATHOLOGY,HBA1C,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
12,60224472_12,PATHOLOGY,PATHOLOGY,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
13,60224472_13,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
14,60224472_14,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
15,60224472_15,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
16,60224472_16,PATHOLOGY,HDL,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
17,60224472_17,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
18,60224472_18,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
19,60224472_19,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
20,60224472_20,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
21,60224472_21,PATHOLOGY,URINE COTININE,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
22,60224472_22,,,,,0.0,,[],0.25,NaN

In [87]:
data = df1.merge(json_df, how='left', left_on='file_name', right_on='key')
data

,classification_1,classification_2,classification_3,file_name,key,class,sub_class,features,name,age,gender,mask,name_match_score,doc_date
0,"{""type"": ""text"", ""title"": ""classification_1"", ...","{""type"": ""text"", ""title"": ""classification_2"", ...","{""type"": ""text"", ""title"": ""classification_3"", ...","{""type"": ""text"", ""title"": ""file_name"", ""name"":...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ECG,NaN,NaN,60224472_0,60224472_0,ECG,,,Bharani Raj Thiagarajan,44.0,male,[],0.25,05012025
2,AADHAAR,NaN,NaN,60224472_1,60224472_1,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.17,20031980
3,AADHAAR,NaN,NaN,60224472_2,60224472_2,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.25,NaN
4,TRF,NaN,NaN,60224472_3,60224472_3,STATIC_FORM,TRF,,NaN,NaN,NaN,[],0.25,08NaN2011
5,MER,NaN,NaN,60224472_4,60224472_4,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,20031980
6,MER,NaN,NaN,60224472_5,60224472_5,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,NaN
7,MER,NaN,NaN,60224472_6,60224472_6,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,08012025
8,PHOTO,NaN,NaN,60224472_7,60224472_7,PHOTO,,"[""face"", ""geo_tag"", ""full_body_image""]",NaN,NaN,NaN,[],0.25,05012025
9,CBC,PATHOLOGY,NaN,60224472_8,60224472_8,PATHOLOGY,CBC|PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
10,CBC,PATHOLOGY,NaN,60224472_9,60224472_9,PATHOLOGY,CBC,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
11,PATHOLOGY,NaN,NaN,60224472_10,60224472_10,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
12,HBA1C,PATHOLOGY,NaN,60224472_11,60224472_11,PATHOLOGY,HBA1C,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
13,PATHOLOGY,NaN,NaN,60224472_12,60224472_12,PATHOLOGY,PATHOLOGY,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
14,PATHOLOGY,NaN,NaN,60224472_13,60224472_13,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
15,PATHOLOGY,NaN,NaN,60224472_14,60224472_14,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
16,PATHOLOGY,NaN,NaN,60224472_15,60224472_15,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
17,HDL,PATHOLOGY,NaN,60224472_16,60224472_16,PATHOLOGY,HDL,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
18,PATHOLOGY,NaN,NaN,60224472_17,60224472_17,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
19,PATHOLOGY,NaN,NaN,60224472_18,60224472_18,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
20,RUA-MX,PATHOLOGY,NaN,60224472_19,60224472_19,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
21,RUA-MX,PATHOLOGY,NaN,60224472_20,60224472_20,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
22,URINE COTININE,PATHOLOGY,NaN,60224472_21,60224472_21,PATHOLOGY,URINE COTININE,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
23,IGNORE,NaN,NaN,60224472_22,60224472_22,,,,,0.0,,[],0.25,NaN

In [88]:
data = data.drop(index=0)

data = data.reset_index(drop=True)
data

,classification_1,classification_2,classification_3,file_name,key,class,sub_class,features,name,age,gender,mask,name_match_score,doc_date
0,ECG,NaN,NaN,60224472_0,60224472_0,ECG,,,Bharani Raj Thiagarajan,44.0,male,[],0.25,05012025
1,AADHAAR,NaN,NaN,60224472_1,60224472_1,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.17,20031980
2,AADHAAR,NaN,NaN,60224472_2,60224472_2,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.25,NaN
3,TRF,NaN,NaN,60224472_3,60224472_3,STATIC_FORM,TRF,,NaN,NaN,NaN,[],0.25,08NaN2011
4,MER,NaN,NaN,60224472_4,60224472_4,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,20031980
5,MER,NaN,NaN,60224472_5,60224472_5,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,NaN
6,MER,NaN,NaN,60224472_6,60224472_6,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,08012025
7,PHOTO,NaN,NaN,60224472_7,60224472_7,PHOTO,,"[""face"", ""geo_tag"", ""full_body_image""]",NaN,NaN,NaN,[],0.25,05012025
8,CBC,PATHOLOGY,NaN,60224472_8,60224472_8,PATHOLOGY,CBC|PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
9,CBC,PATHOLOGY,NaN,60224472_9,60224472_9,PATHOLOGY,CBC,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
10,PATHOLOGY,NaN,NaN,60224472_10,60224472_10,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
11,HBA1C,PATHOLOGY,NaN,60224472_11,60224472_11,PATHOLOGY,HBA1C,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
12,PATHOLOGY,NaN,NaN,60224472_12,60224472_12,PATHOLOGY,PATHOLOGY,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
13,PATHOLOGY,NaN,NaN,60224472_13,60224472_13,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
14,PATHOLOGY,NaN,NaN,60224472_14,60224472_14,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
15,PATHOLOGY,NaN,NaN,60224472_15,60224472_15,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
16,HDL,PATHOLOGY,NaN,60224472_16,60224472_16,PATHOLOGY,HDL,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
17,PATHOLOGY,NaN,NaN,60224472_17,60224472_17,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
18,PATHOLOGY,NaN,NaN,60224472_18,60224472_18,PATHOLOGY,,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
19,RUA-MX,PATHOLOGY,NaN,60224472_19,60224472_19,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
20,RUA-MX,PATHOLOGY,NaN,60224472_20,60224472_20,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
21,URINE COTININE,PATHOLOGY,NaN,60224472_21,60224472_21,PATHOLOGY,URINE COTININE,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
22,IGNORE,NaN,NaN,60224472_22,60224472_22,,,,,0.0,,[],0.25,NaN

In [89]:
data["sub_class"] = data["sub_class"].replace('', 'IGNORE')
data

,classification_1,classification_2,classification_3,file_name,key,class,sub_class,features,name,age,gender,mask,name_match_score,doc_date
0,ECG,NaN,NaN,60224472_0,60224472_0,ECG,IGNORE,,Bharani Raj Thiagarajan,44.0,male,[],0.25,05012025
1,AADHAAR,NaN,NaN,60224472_1,60224472_1,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.17,20031980
2,AADHAAR,NaN,NaN,60224472_2,60224472_2,ID_CARD,AADHAAR,,NaN,NaN,NaN,[],0.25,NaN
3,TRF,NaN,NaN,60224472_3,60224472_3,STATIC_FORM,TRF,,NaN,NaN,NaN,[],0.25,08NaN2011
4,MER,NaN,NaN,60224472_4,60224472_4,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,20031980
5,MER,NaN,NaN,60224472_5,60224472_5,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,NaN
6,MER,NaN,NaN,60224472_6,60224472_6,STATIC_FORM,MER,,NaN,NaN,NaN,[],0.25,08012025
7,PHOTO,NaN,NaN,60224472_7,60224472_7,PHOTO,IGNORE,"[""face"", ""geo_tag"", ""full_body_image""]",NaN,NaN,NaN,[],0.25,05012025
8,CBC,PATHOLOGY,NaN,60224472_8,60224472_8,PATHOLOGY,CBC|PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
9,CBC,PATHOLOGY,NaN,60224472_9,60224472_9,PATHOLOGY,CBC,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
10,PATHOLOGY,NaN,NaN,60224472_10,60224472_10,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
11,HBA1C,PATHOLOGY,NaN,60224472_11,60224472_11,PATHOLOGY,HBA1C,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
12,PATHOLOGY,NaN,NaN,60224472_12,60224472_12,PATHOLOGY,PATHOLOGY,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
13,PATHOLOGY,NaN,NaN,60224472_13,60224472_13,PATHOLOGY,IGNORE,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
14,PATHOLOGY,NaN,NaN,60224472_14,60224472_14,PATHOLOGY,IGNORE,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.33,NaN
15,PATHOLOGY,NaN,NaN,60224472_15,60224472_15,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
16,HDL,PATHOLOGY,NaN,60224472_16,60224472_16,PATHOLOGY,HDL,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
17,PATHOLOGY,NaN,NaN,60224472_17,60224472_17,PATHOLOGY,PATHOLOGY,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
18,PATHOLOGY,NaN,NaN,60224472_18,60224472_18,PATHOLOGY,IGNORE,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
19,RUA-MX,PATHOLOGY,NaN,60224472_19,60224472_19,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
20,RUA-MX,PATHOLOGY,NaN,60224472_20,60224472_20,PATHOLOGY,RUA-MX,,Mr Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
21,URINE COTININE,PATHOLOGY,NaN,60224472_21,60224472_21,PATHOLOGY,URINE COTININE,,Bharani Raj Thiagarajan,44.0,male,[],0.25,NaN
22,IGNORE,NaN,NaN,60224472_22,60224472_22,,IGNORE,,,0.0,,[],0.25,NaN

In [90]:
accuracy_results = defaultdict(list)
total_predictions = len(data)
correct_predictions = 0

In [91]:
import numpy as np
for index, row in data.iterrows():
    subclass = row.get('sub_class', 'Unknown')
    classifications = [
        row.get('classification_1', ''),
        row.get('classification_2', ''),
        row.get('classification_3', ''),
    ]

    # Exceptional cases for accurate predictions
    if pd.isna(subclass) or subclass in ['CBC|PATHOLOGY', 'IGNORE']:
        correct_predictions += 1
        accuracy_results[subclass].append(True)
    elif subclass in classifications:
        correct_predictions += 1
        accuracy_results[subclass].append(True)
    else:
        accuracy_results[subclass].append(False)

In [95]:
if total_predictions > 0:
    overall_accuracy = (correct_predictions / total_predictions) * 100
else:
    overall_accuracy = 0

print(f"Overall Accuracy: {overall_accuracy:.2f}%")

Overall Accuracy: 100.00%

In [96]:
# unique file processing per day

file_processing_per_day = json_df['key'].nunique()

In [97]:
accuracy_by_sub_class = {subclass: (sum(matches) / len(matches)) * 100 for subclass, matches in accuracy_results.items()}
accuracy_df = pd.DataFrame(list(accuracy_by_sub_class.items()), columns=['Sub-Class', 'Accuracy (%)'])
print("Accuracy by Sub-Class:\n", accuracy_df.to_string(index=False))

Accuracy by Sub-Class:
      Sub-Class  Accuracy (%)
        IGNORE         100.0
       AADHAAR         100.0
           TRF         100.0
           MER         100.0
 CBC|PATHOLOGY         100.0
           CBC         100.0
     PATHOLOGY         100.0
         HBA1C         100.0
           HDL         100.0
        RUA-MX         100.0
URINE COTININE         100.0

In [101]:
#results for reporting
report = {
    'accuracy_by_sub_class': {subclass: (sum(matches) / len(matches)) * 100 for subclass, matches in accuracy_results.items()},
    'overall_accuracy': f"{overall_accuracy:.2f}%",
    'Pages_processing_per_day': file_processing_per_day,
}

In [102]:
report

{'accuracy_by_sub_class': {'IGNORE': 100.0,
  'AADHAAR': 100.0,
  'TRF': 100.0,
  'MER': 100.0,
  'CBC|PATHOLOGY': 100.0,
  'CBC': 100.0,
  'PATHOLOGY': 100.0,
  'HBA1C': 100.0,
  'HDL': 100.0,
  'RUA-MX': 100.0,
  'URINE COTININE': 100.0},
 'overall_accuracy': '100.00%',
 'Pages_processing_per_day': 23}

In [103]:
data["sub_class"].unique()

array(['IGNORE', 'AADHAAR', 'TRF', 'MER', 'CBC|PATHOLOGY', 'CBC',
       'PATHOLOGY', 'HBA1C', 'HDL', 'RUA-MX', 'URINE COTININE'],
      dtype=object)

In [104]:
import csv
from datetime import datetime
output_file = "report.csv"
current_date = datetime.now().strftime("%Y-%m-%d")

# Flatten and write the report data to a CSV file
with open(output_file, mode="w", newline="") as file:
    writer = csv.writer(file)

    writer.writerow(["Report Generation Date", current_date])
    writer.writerow([])

    # Write overall accuracy
    writer.writerow(["Metric", "Value"])
    writer.writerow(["Overall Accuracy", report['overall_accuracy']])
    writer.writerow(["Total Pages Processed Per Day", report['Pages_processing_per_day']])
    writer.writerow([])  # Empty row for spacing

    # Write accuracy by sub-class
    writer.writerow(["Sub Class", "Accuracy (%)"])
    for subclass, accuracy in report['accuracy_by_sub_class'].items():
        writer.writerow([subclass, accuracy])

print(f"Report successfully written to {output_file}")

Report successfully written to report.csv

In [110]:
import csv

# Function to generate HTML page from CSV data
def generate_html(csv_file, output_html):
    with open(csv_file, mode='r') as file:
        reader = csv.reader(file)

        # Extract all rows
        rows = list(reader)

    # Start HTML structure
    html_content = '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Report Summary</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                background-color: #f4f4f4;
            }
            h1 {
                text-align: center;
            }
            table {
                width: 50%;
                margin: 20px auto;
                border-collapse: collapse;
            }
            th, td {
                padding: 5px;
                border: 1px solid #ccc;
                text-align: left;
            }
            th {
                background-color: #f2f2f2;
            }
            .section-title {
                font-size: 1.5em;
                margin-top: 40px;
                text-align: center;
            }
            .logo {
                position: absolute;
                top: 10px;  /* Adjust to position from the top */
                right: 10px;  /* Adjust to position from the right */
                width: 60px;  /* Smaller logo size */
            }
        </style>
    </head>
    <body>

        <img src="logo.png" alt="Company Logo" class="logo">

        <h1>Report Summary</h1>
    '''

    # Process CSV data for Report Generation Date
    report_generation_date = rows[0][1]
    html_content += f'''
    <table>
        <tr>
            <th>Report Generation Date</th>
            <td>{report_generation_date}</td>
        </tr>
    </table>
    '''

    # Process Overall Metrics
    html_content += '<div class="section-title">Overall Metrics</div><table><tr><th>Metric</th><th>Value</th></tr>'
    for row in rows[3:5]:
        html_content += f'<tr><td>{row[0]}</td><td>{row[1]}</td></tr>'
    html_content += '</table>'

    # Process Sub Class Accuracy
    html_content += '<div class="section-title">Sub Class Accuracy</div><table><tr><th>Sub Class</th><th>Accuracy (%)</th></tr>'
    for row in rows[7:]:
        if row:
            accuracy_value = float(row[1])
            html_content += f'<tr><td>{row[0]}</td><td>{accuracy_value:.2f}%</td></tr>'
    html_content += '</table>'

    # End HTML structure
    html_content += '''
    </body>
    </html>
    '''

    # Write the HTML content to a file
    with open(output_html, 'w') as output_file:
        output_file.write(html_content)

# Call the function to generate HTML
generate_html('report.csv', 'output_report.html')